// DDL PostgreSQL cho tầng nội dung pháp lý — port 1:1 từ bootstrap SQLite
// (db/index.ts bản D1 cũ). Mỗi phần tử là MỘT câu lệnh vì driver neon-http
// chỉ chạy một statement mỗi request. Toàn bộ idempotent (IF NOT EXISTS /
// CREATE OR REPLACE) — chạy lại bao nhiêu lần cũng an toàn.
//
// Khác biệt cú pháp so với SQLite đã xử lý:
// - GLOB → biểu thức chính quy POSIX (~)
// - IS NOT → IS DISTINCT FROM
// - RAISE(ABORT, ...) → RAISE EXCEPTION trong hàm plpgsql
// - WHEN của trigger chuyển hết vào thân hàm (PG cấm subquery trong WHEN)

const createLegalSourcesTable = `
CREATE TABLE IF NOT EXISTS legal_sources (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  document_number text NOT NULL,
  title text NOT NULL,
  official_url text NOT NULL,
  official_host text NOT NULL,
  issued_at text,
  effective_from text,
  effective_to text,
  status text DEFAULT 'draft' NOT NULL,
  created_by text NOT NULL,
  last_verified_at text,
  verified_by text,
  created_at text DEFAULT (now())::text NOT NULL,
  updated_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT legal_sources_status_check
    CHECK (status IN ('draft', 'in_force', 'expired', 'superseded')),
  CONSTRAINT legal_sources_https_url_check
    CHECK (lower(official_url) LIKE 'https://%'),
  CONSTRAINT legal_sources_official_host_format_check
    CHECK (
      official_host = lower(official_host)
      AND length(official_host) > 0
      AND official_host ~ '^[a-z0-9.-]+$'
      AND official_host NOT LIKE '%..%'
      AND official_host NOT LIKE '.%'
      AND official_host NOT LIKE '%.'
    ),
  CONSTRAINT legal_sources_official_host_allowlist_check
    CHECK (status = 'draft' OR (
      official_host IN ('vbpl.vn', 'vbpl.moj.gov.vn', 'chinhphu.vn')
      OR official_host LIKE '%.chinhphu.vn'
    )),
  CONSTRAINT legal_sources_url_authority_check
    CHECK (
      lower(official_url) = 'https://' || official_host
      OR lower(official_url) LIKE 'https://' || official_host || '/%'
      OR lower(official_url) LIKE 'https://' || official_host || '?%'
      OR lower(official_url) LIKE 'https://' || official_host || '#%'
    ),
  CONSTRAINT legal_sources_effectivity_check
    CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from),
  CONSTRAINT legal_sources_in_force_verification_check
    CHECK (status != 'in_force' OR (
      effective_from IS NOT NULL
      AND last_verified_at IS NOT NULL
      AND verified_by IS NOT NULL
      AND verified_by != created_by
    ))
)`;

const createLegalProvisionsTable = `
CREATE TABLE IF NOT EXISTS legal_provisions (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  source_id integer NOT NULL,
  article text,
  clause text,
  point text,
  original_text text NOT NULL,
  simplified_text text NOT NULL,
  status text DEFAULT 'draft' NOT NULL,
  created_by text NOT NULL,
  reviewed_by text,
  reviewed_at text,
  revision_id text,
  checksum_version text,
  checksum_sha256 text,
  effectivity_status text DEFAULT 'unknown' NOT NULL,
  effective_from text,
  effective_to text,
  created_at text DEFAULT (now())::text NOT NULL,
  updated_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT legal_provisions_source_id_legal_sources_id_fk
    FOREIGN KEY (source_id) REFERENCES legal_sources(id)
    ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT legal_provisions_status_check
    CHECK (status IN ('draft', 'pending_review', 'published', 'archived')),
  CONSTRAINT legal_provisions_published_review_check
    CHECK (status != 'published' OR (
      reviewed_by IS NOT NULL
      AND reviewed_at IS NOT NULL
      AND reviewed_by != created_by
    )),
  CONSTRAINT legal_provisions_effectivity_status_check
    CHECK (effectivity_status IN (
      'unknown', 'in_force', 'partially_in_force', 'superseded', 'expired'
    )),
  CONSTRAINT legal_provisions_effectivity_window_check
    CHECK (
      effective_to IS NULL
      OR effective_from IS NOT NULL AND effective_to >= effective_from
    ),
  CONSTRAINT legal_provisions_revision_metadata_check
    CHECK (
      (
        revision_id IS NULL
        AND checksum_version IS NULL
        AND checksum_sha256 IS NULL
      ) OR (
        revision_id IS NOT NULL
        AND length(revision_id) BETWEEN 1 AND 128
        AND revision_id ~ '^[A-Za-z0-9]'
        AND revision_id ~ '^[A-Za-z0-9._:-]+$'
        AND checksum_version = 'provision-sha256-v1'
        AND checksum_sha256 ~ '^[0-9a-f]{64}$'
      )
    ),
  CONSTRAINT legal_provisions_published_readiness_check
    CHECK (status != 'published' OR (
      revision_id IS NOT NULL
      AND checksum_version = 'provision-sha256-v1'
      AND checksum_sha256 IS NOT NULL
      AND effectivity_status = 'in_force'
      AND effective_from IS NOT NULL
    ))
)`;

const createLegalEntriesTable = `
CREATE TABLE IF NOT EXISTS legal_entries (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  topic text NOT NULL,
  icon text DEFAULT '§' NOT NULL,
  title text NOT NULL,
  legal_basis text NOT NULL,
  penalty text NOT NULL,
  remedy text NOT NULL,
  case_study text NOT NULL,
  tags text DEFAULT '[]' NOT NULL,
  media_url text DEFAULT '' NOT NULL,
  status text DEFAULT 'draft' NOT NULL,
  review_status text DEFAULT 'legacy_unverified' NOT NULL,
  created_by text,
  reviewed_by text,
  reviewed_at text,
  created_at text DEFAULT (now())::text NOT NULL,
  updated_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT legal_entries_status_check
    CHECK (status IN ('draft', 'published')),
  CONSTRAINT legal_entries_review_status_check
    CHECK (review_status IN ('legacy_unverified', 'four_eyes_verified')),
  CONSTRAINT legal_entries_four_eyes_review_check
    CHECK (review_status != 'four_eyes_verified' OR (
      status = 'published'
      AND created_by IS NOT NULL
      AND reviewed_by IS NOT NULL
      AND reviewed_at IS NOT NULL
      AND reviewed_by != created_by
    ))
)`;

const createLegalEntryCitationsTable = `
CREATE TABLE IF NOT EXISTS legal_entry_citations (
  legal_entry_id integer NOT NULL,
  provision_id integer NOT NULL,
  display_order integer DEFAULT 0 NOT NULL,
  review_status text DEFAULT 'legacy_unverified' NOT NULL,
  created_by text,
  reviewed_by text,
  reviewed_at text,
  cited_revision_id text,
  cited_checksum_version text,
  cited_checksum_sha256 text,
  created_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT legal_entry_citations_pk
    PRIMARY KEY (legal_entry_id, provision_id),
  CONSTRAINT legal_entry_citations_legal_entry_id_legal_entries_id_fk
    FOREIGN KEY (legal_entry_id) REFERENCES legal_entries(id)
    ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT legal_entry_citations_provision_id_legal_provisions_id_fk
    FOREIGN KEY (provision_id) REFERENCES legal_provisions(id)
    ON UPDATE NO ACTION ON DELETE RESTRICT,
  CONSTRAINT legal_entry_citations_display_order_check
    CHECK (display_order >= 0),
  CONSTRAINT legal_entry_citations_review_status_check
    CHECK (review_status IN ('legacy_unverified', 'four_eyes_verified')),
  CONSTRAINT legal_entry_citations_four_eyes_review_check
    CHECK (review_status != 'four_eyes_verified' OR (
      created_by IS NOT NULL
      AND reviewed_by IS NOT NULL
      AND reviewed_at IS NOT NULL
      AND reviewed_by != created_by
      AND cited_revision_id IS NOT NULL
      AND cited_checksum_version = 'provision-sha256-v1'
      AND cited_checksum_sha256 IS NOT NULL
    ))
)`;

const createShowcasesTable = `
CREATE TABLE IF NOT EXISTS showcases (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  topic text NOT NULL,
  title text NOT NULL,
  summary text NOT NULL,
  source_url text DEFAULT '' NOT NULL,
  media_url text DEFAULT '' NOT NULL,
  status text DEFAULT 'draft' NOT NULL,
  created_at text DEFAULT (now())::text NOT NULL,
  updated_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT showcases_status_check
    CHECK (status IN ('draft', 'published'))
)`;

// Bộ đếm tương tác công khai (US-033 lượt xem, US-034 "Nội dung này ý nghĩa").
// Bảng đếm không lưu định danh người dùng; bảng mark chỉ lưu hash một chiều.
const createContentEngagementTable = `
CREATE TABLE IF NOT EXISTS content_engagement (
  entity_type text NOT NULL,
  entity_id integer NOT NULL,
  view_count integer DEFAULT 0 NOT NULL,
  favorite_count integer DEFAULT 0 NOT NULL,
  updated_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT content_engagement_pk PRIMARY KEY (entity_type, entity_id),
  CONSTRAINT content_engagement_entity_type_check
    CHECK (entity_type IN ('law', 'showcase')),
  CONSTRAINT content_engagement_entity_id_check
    CHECK (entity_id > 0),
  CONSTRAINT content_engagement_counts_check
    CHECK (view_count >= 0 AND favorite_count >= 0)
)`;

const createContentEngagementMarksTable = `
CREATE TABLE IF NOT EXISTS content_engagement_marks (
  mark_key text PRIMARY KEY,
  expires_at integer,
  created_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT content_engagement_marks_key_check
    CHECK (mark_key ~ '^[0-9a-f]{64}$')
)`;

// Game hóa (US-035 quiz/điểm/huy hiệu, US-036 nhập vai). Ngân hàng câu hỏi,
// kịch bản và cấu hình quy đổi đều là dữ liệu do CMS quản lý.
const createQuizQuestionsTable = `
CREATE TABLE IF NOT EXISTS quiz_questions (
  id serial PRIMARY KEY,
  topic text NOT NULL,
  prompt text NOT NULL,
  options text NOT NULL,
  correct_index integer DEFAULT 0 NOT NULL,
  explanation text NOT NULL,
  legal_basis text NOT NULL,
  source_url text DEFAULT '' NOT NULL,
  points integer DEFAULT 10 NOT NULL,
  status text DEFAULT 'draft' NOT NULL,
  created_at text DEFAULT (now())::text NOT NULL,
  updated_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT quiz_questions_status_check
    CHECK (status IN ('draft', 'published')),
  CONSTRAINT quiz_questions_correct_index_check
    CHECK (correct_index >= 0 AND correct_index < 4),
  CONSTRAINT quiz_questions_points_check
    CHECK (points >= 1 AND points <= 100)
)`;

const createRoleplayScenariosTable = `
CREATE TABLE IF NOT EXISTS roleplay_scenarios (
  id serial PRIMARY KEY,
  topic text NOT NULL,
  title text NOT NULL,
  intro text NOT NULL,
  start_key text NOT NULL,
  status text DEFAULT 'draft' NOT NULL,
  created_at text DEFAULT (now())::text NOT NULL,
  updated_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT roleplay_scenarios_status_check
    CHECK (status IN ('draft', 'published')),
  CONSTRAINT roleplay_scenarios_start_key_check
    CHECK (start_key ~ '^[a-z0-9][a-z0-9-]{0,39}$')
)`;

const createRoleplayNodesTable = `
CREATE TABLE IF NOT EXISTS roleplay_nodes (
  scenario_id integer NOT NULL REFERENCES roleplay_scenarios (id) ON DELETE CASCADE,
  node_key text NOT NULL,
  kind text DEFAULT 'step' NOT NULL,
  text text NOT NULL,
  choices text DEFAULT '[]' NOT NULL,
  consequence text DEFAULT '' NOT NULL,
  legal_basis text DEFAULT '' NOT NULL,
  source_url text DEFAULT '' NOT NULL,
  outcome_kind text,
  points integer DEFAULT 1 NOT NULL,
  created_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT roleplay_nodes_pk PRIMARY KEY (scenario_id, node_key),
  CONSTRAINT roleplay_nodes_node_key_check
    CHECK (node_key ~ '^[a-z0-9][a-z0-9-]{0,39}$'),
  CONSTRAINT roleplay_nodes_kind_check
    CHECK (kind IN ('step', 'outcome')),
  CONSTRAINT roleplay_nodes_outcome_kind_check
    CHECK (outcome_kind IS NULL OR outcome_kind IN ('safe', 'risky', 'harmful')),
  CONSTRAINT roleplay_nodes_points_check
    CHECK (points >= 1 AND points <= 100)
)`;

// Cấu hình quy đổi điểm sang huy hiệu.
const createGameBadgesTable = `
CREATE TABLE IF NOT EXISTS game_badges (
  code text PRIMARY KEY,
  name text NOT NULL,
  icon text DEFAULT '★' NOT NULL,
  description text DEFAULT '' NOT NULL,
  threshold_points integer NOT NULL,
  updated_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT game_badges_code_check
    CHECK (code ~ '^[a-z0-9][a-z0-9-]{0,39}$'),
  CONSTRAINT game_badges_threshold_check
    CHECK (threshold_points > 0)
)`;

// Tiến độ người chơi: khóa là SHA-256 của token ngẫu nhiên do trình duyệt tự
// sinh, không lưu bất kỳ định danh cá nhân nào.
const createGameProgressTable = `
CREATE TABLE IF NOT EXISTS game_progress (
  player_key text PRIMARY KEY,
  points integer DEFAULT 0 NOT NULL,
  updated_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT game_progress_player_key_check
    CHECK (player_key ~ '^[0-9a-f]{64}$'),
  CONSTRAINT game_progress_points_check
    CHECK (points >= 0)
)`;

// Dấu chống cộng điểm trùng cho mỗi (người chơi, câu hỏi/kết cục).
const createGameAwardsTable = `
CREATE TABLE IF NOT EXISTS game_awards (
  award_key text PRIMARY KEY,
  created_at text DEFAULT (now())::text NOT NULL,
  CONSTRAINT game_awards_key_check
    CHECK (award_key ~ '^[0-9a-f]{64}$')
)`;

const indexStatements = [
  `CREATE INDEX IF NOT EXISTS quiz_questions_topic_status_idx
   ON quiz_questions (topic, status)`,
  `CREATE INDEX IF NOT EXISTS roleplay_nodes_scenario_idx
   ON roleplay_nodes (scenario_id)`,
  `CREATE INDEX IF NOT EXISTS content_engagement_marks_expires_at_idx
   ON content_engagement_marks (expires_at)
   WHERE expires_at IS NOT NULL`,
  `CREATE UNIQUE INDEX IF NOT EXISTS legal_sources_document_number_unique
   ON legal_sources (document_number)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS legal_sources_official_url_unique
   ON legal_sources (official_url)`,
  `CREATE INDEX IF NOT EXISTS legal_sources_status_idx
   ON legal_sources (status)`,
  `CREATE INDEX IF NOT EXISTS legal_provisions_source_id_idx
   ON legal_provisions (source_id)`,
  `CREATE INDEX IF NOT EXISTS legal_provisions_status_idx
   ON legal_provisions (status)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS legal_provisions_revision_id_unique
   ON legal_provisions (revision_id)
   WHERE revision_id IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS legal_entry_citations_provision_id_idx
   ON legal_entry_citations (provision_id)`,
];

// ===== Hàm + trigger plpgsql =====

const triggerStatements = [
  `CREATE OR REPLACE FUNCTION legal_sources_created_by_immutable_fn()
   RETURNS trigger AS $$
   BEGIN
     IF NEW.created_by IS DISTINCT FROM OLD.created_by THEN
       RAISE EXCEPTION 'legal source created_by is immutable';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_sources_created_by_immutable
   BEFORE UPDATE OF created_by ON legal_sources
   FOR EACH ROW EXECUTE FUNCTION legal_sources_created_by_immutable_fn()`,

  `CREATE OR REPLACE FUNCTION legal_provisions_created_by_immutable_fn()
   RETURNS trigger AS $$
   BEGIN
     IF NEW.created_by IS DISTINCT FROM OLD.created_by THEN
       RAISE EXCEPTION 'legal provision created_by is immutable';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_provisions_created_by_immutable
   BEFORE UPDATE OF created_by ON legal_provisions
   FOR EACH ROW EXECUTE FUNCTION legal_provisions_created_by_immutable_fn()`,

  `CREATE OR REPLACE FUNCTION legal_entries_created_by_immutable_fn()
   RETURNS trigger AS $$
   BEGIN
     IF OLD.created_by IS NOT NULL
        AND NEW.created_by IS DISTINCT FROM OLD.created_by THEN
       RAISE EXCEPTION 'legal entry created_by is immutable';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_entries_created_by_immutable
   BEFORE UPDATE OF created_by ON legal_entries
   FOR EACH ROW EXECUTE FUNCTION legal_entries_created_by_immutable_fn()`,

  `CREATE OR REPLACE FUNCTION legal_entries_review_check_fn()
   RETURNS trigger AS $$
   BEGIN
     IF (
       NEW.review_status = 'legacy_unverified'
       AND (NEW.reviewed_by IS NOT NULL OR NEW.reviewed_at IS NOT NULL)
     ) OR (
       NEW.review_status = 'four_eyes_verified'
       AND (
         NEW.status != 'published'
         OR NEW.created_by IS NULL
         OR length(trim(NEW.created_by)) = 0
         OR NEW.reviewed_by IS NULL
         OR length(trim(NEW.reviewed_by)) = 0
         OR NEW.reviewed_at IS NULL
         OR NEW.reviewed_by = NEW.created_by
       )
     ) THEN
       RAISE EXCEPTION 'invalid legal entry review metadata';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_entries_review_insert_check
   BEFORE INSERT ON legal_entries
   FOR EACH ROW EXECUTE FUNCTION legal_entries_review_check_fn()`,
  `CREATE OR REPLACE TRIGGER legal_entries_review_update_check
   BEFORE UPDATE ON legal_entries
   FOR EACH ROW EXECUTE FUNCTION legal_entries_review_check_fn()`,

  `CREATE OR REPLACE FUNCTION legal_entries_material_invalidation_fn()
   RETURNS trigger AS $$
   BEGIN
     IF NEW.topic IS DISTINCT FROM OLD.topic
        OR NEW.icon IS DISTINCT FROM OLD.icon
        OR NEW.title IS DISTINCT FROM OLD.title
        OR NEW.legal_basis IS DISTINCT FROM OLD.legal_basis
        OR NEW.penalty IS DISTINCT FROM OLD.penalty
        OR NEW.remedy IS DISTINCT FROM OLD.remedy
        OR NEW.case_study IS DISTINCT FROM OLD.case_study
        OR NEW.tags IS DISTINCT FROM OLD.tags THEN
       UPDATE legal_entries
       SET review_status = 'legacy_unverified',
           reviewed_by = NULL,
           reviewed_at = NULL,
           updated_at = (now())::text
       WHERE id = NEW.id
         AND review_status = 'four_eyes_verified';
       UPDATE legal_entry_citations
       SET review_status = 'legacy_unverified',
           reviewed_by = NULL,
           reviewed_at = NULL
       WHERE legal_entry_id = NEW.id;
     END IF;
     RETURN NULL;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_entries_material_change_invalidates_review
   AFTER UPDATE OF topic, icon, title, legal_basis, penalty, remedy, case_study, tags
   ON legal_entries
   FOR EACH ROW EXECUTE FUNCTION legal_entries_material_invalidation_fn()`,

  `CREATE OR REPLACE FUNCTION legal_provisions_revision_immutable_fn()
   RETURNS trigger AS $$
   BEGIN
     IF OLD.revision_id IS NOT NULL AND (
       NEW.source_id IS DISTINCT FROM OLD.source_id
       OR NEW.article IS DISTINCT FROM OLD.article
       OR NEW.clause IS DISTINCT FROM OLD.clause
       OR NEW.point IS DISTINCT FROM OLD.point
       OR NEW.original_text IS DISTINCT FROM OLD.original_text
       OR NEW.simplified_text IS DISTINCT FROM OLD.simplified_text
       OR NEW.revision_id IS DISTINCT FROM OLD.revision_id
       OR NEW.checksum_version IS DISTINCT FROM OLD.checksum_version
       OR NEW.checksum_sha256 IS DISTINCT FROM OLD.checksum_sha256
       OR NEW.effectivity_status IS DISTINCT FROM OLD.effectivity_status
       OR NEW.effective_from IS DISTINCT FROM OLD.effective_from
       OR NEW.effective_to IS DISTINCT FROM OLD.effective_to
     ) THEN
       RAISE EXCEPTION 'provision revision is immutable';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_provisions_revision_immutable
   BEFORE UPDATE OF source_id, article, clause, point, original_text,
     simplified_text, revision_id, checksum_version, checksum_sha256,
     effectivity_status, effective_from, effective_to
   ON legal_provisions
   FOR EACH ROW EXECUTE FUNCTION legal_provisions_revision_immutable_fn()`,

  `CREATE OR REPLACE FUNCTION legal_provisions_published_source_check_fn()
   RETURNS trigger AS $$
   BEGIN
     IF NEW.status = 'published' AND NOT EXISTS (
       SELECT 1
       FROM legal_sources
       WHERE id = NEW.source_id
         AND status = 'in_force'
         AND effective_from IS NOT NULL
         AND last_verified_at IS NOT NULL
         AND verified_by IS NOT NULL
         AND verified_by != created_by
     ) THEN
       RAISE EXCEPTION 'published provision requires an in-force verified source';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_provisions_published_source_insert_check
   BEFORE INSERT ON legal_provisions
   FOR EACH ROW EXECUTE FUNCTION legal_provisions_published_source_check_fn()`,
  `CREATE OR REPLACE TRIGGER legal_provisions_published_source_update_check
   BEFORE UPDATE ON legal_provisions
   FOR EACH ROW EXECUTE FUNCTION legal_provisions_published_source_check_fn()`,

  `CREATE OR REPLACE FUNCTION legal_sources_invalidate_provisions_fn()
   RETURNS trigger AS $$
   BEGIN
     IF NOT (
       NEW.status = 'in_force'
       AND NEW.effective_from IS NOT NULL
       AND NEW.last_verified_at IS NOT NULL
       AND NEW.verified_by IS NOT NULL
       AND NEW.verified_by != NEW.created_by
     ) THEN
       UPDATE legal_provisions
       SET status = 'pending_review',
           reviewed_by = NULL,
           reviewed_at = NULL,
           updated_at = (now())::text
       WHERE source_id = NEW.id
         AND status = 'published';
     END IF;
     RETURN NULL;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_sources_invalidate_published_provisions
   AFTER UPDATE ON legal_sources
   FOR EACH ROW EXECUTE FUNCTION legal_sources_invalidate_provisions_fn()`,

  `CREATE OR REPLACE FUNCTION legal_entry_citations_relation_immutable_fn()
   RETURNS trigger AS $$
   BEGIN
     IF NEW.legal_entry_id IS DISTINCT FROM OLD.legal_entry_id
        OR NEW.provision_id IS DISTINCT FROM OLD.provision_id THEN
       RAISE EXCEPTION 'citation relation is immutable';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_entry_citations_relation_immutable
   BEFORE UPDATE OF legal_entry_id, provision_id ON legal_entry_citations
   FOR EACH ROW EXECUTE FUNCTION legal_entry_citations_relation_immutable_fn()`,

  `CREATE OR REPLACE FUNCTION legal_entry_citations_created_by_immutable_fn()
   RETURNS trigger AS $$
   BEGIN
     IF OLD.created_by IS NOT NULL
        AND NEW.created_by IS DISTINCT FROM OLD.created_by THEN
       RAISE EXCEPTION 'citation created_by is immutable';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_entry_citations_created_by_immutable
   BEFORE UPDATE OF created_by ON legal_entry_citations
   FOR EACH ROW EXECUTE FUNCTION legal_entry_citations_created_by_immutable_fn()`,

  `CREATE OR REPLACE FUNCTION legal_entry_citations_review_check_fn()
   RETURNS trigger AS $$
   BEGIN
     IF (
       NEW.review_status = 'legacy_unverified'
       AND (NEW.reviewed_by IS NOT NULL OR NEW.reviewed_at IS NOT NULL)
     ) OR (
       NEW.review_status = 'four_eyes_verified'
       AND (
         NEW.created_by IS NULL
         OR length(trim(NEW.created_by)) = 0
         OR NEW.reviewed_by IS NULL
         OR length(trim(NEW.reviewed_by)) = 0
         OR NEW.reviewed_at IS NULL
         OR NEW.reviewed_by = NEW.created_by
         OR NEW.cited_revision_id IS NULL
         OR NEW.cited_checksum_version IS DISTINCT FROM 'provision-sha256-v1'
         OR NEW.cited_checksum_sha256 IS NULL
         OR NOT EXISTS (
           SELECT 1
           FROM legal_entries AS entry
           INNER JOIN legal_provisions AS provision
             ON provision.id = NEW.provision_id
           INNER JOIN legal_sources AS source
             ON source.id = provision.source_id
           WHERE entry.id = NEW.legal_entry_id
             AND entry.status = 'published'
             AND entry.review_status = 'four_eyes_verified'
             AND provision.status = 'published'
             AND provision.revision_id = NEW.cited_revision_id
             AND provision.checksum_version = NEW.cited_checksum_version
             AND provision.checksum_sha256 = NEW.cited_checksum_sha256
             AND provision.effectivity_status = 'in_force'
             AND source.status = 'in_force'
         )
       )
     ) THEN
       RAISE EXCEPTION 'invalid citation review or revision binding';
     END IF;
     RETURN NEW;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_entry_citations_review_insert_check
   BEFORE INSERT ON legal_entry_citations
   FOR EACH ROW EXECUTE FUNCTION legal_entry_citations_review_check_fn()`,
  `CREATE OR REPLACE TRIGGER legal_entry_citations_review_update_check
   BEFORE UPDATE ON legal_entry_citations
   FOR EACH ROW EXECUTE FUNCTION legal_entry_citations_review_check_fn()`,

  `CREATE OR REPLACE FUNCTION legal_entry_citations_binding_invalidation_fn()
   RETURNS trigger AS $$
   BEGIN
     IF OLD.review_status = 'four_eyes_verified' AND (
       NEW.cited_revision_id IS DISTINCT FROM OLD.cited_revision_id
       OR NEW.cited_checksum_version IS DISTINCT FROM OLD.cited_checksum_version
       OR NEW.cited_checksum_sha256 IS DISTINCT FROM OLD.cited_checksum_sha256
     ) THEN
       UPDATE legal_entry_citations
       SET review_status = 'legacy_unverified',
           reviewed_by = NULL,
           reviewed_at = NULL
       WHERE legal_entry_id = NEW.legal_entry_id
         AND provision_id = NEW.provision_id;
     END IF;
     RETURN NULL;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_entry_citations_binding_change_invalidates_review
   AFTER UPDATE OF cited_revision_id, cited_checksum_version, cited_checksum_sha256
   ON legal_entry_citations
   FOR EACH ROW EXECUTE FUNCTION legal_entry_citations_binding_invalidation_fn()`,

  `CREATE OR REPLACE FUNCTION legal_provisions_state_invalidates_citations_fn()
   RETURNS trigger AS $$
   BEGIN
     IF OLD.status = 'published' AND (
       NEW.status != 'published'
       OR NEW.reviewed_by IS NULL
       OR NEW.reviewed_at IS NULL
     ) THEN
       UPDATE legal_entry_citations
       SET review_status = 'legacy_unverified',
           reviewed_by = NULL,
           reviewed_at = NULL
       WHERE provision_id = NEW.id;
     END IF;
     RETURN NULL;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_provisions_state_invalidates_citations
   AFTER UPDATE OF status, reviewed_by, reviewed_at ON legal_provisions
   FOR EACH ROW EXECUTE FUNCTION legal_provisions_state_invalidates_citations_fn()`,

  `CREATE OR REPLACE FUNCTION legal_sources_rag_invalidation_fn()
   RETURNS trigger AS $$
   BEGIN
     IF NEW.document_number IS DISTINCT FROM OLD.document_number
        OR NEW.title IS DISTINCT FROM OLD.title
        OR NEW.official_url IS DISTINCT FROM OLD.official_url
        OR NEW.official_host IS DISTINCT FROM OLD.official_host
        OR NEW.effective_from IS DISTINCT FROM OLD.effective_from
        OR NEW.effective_to IS DISTINCT FROM OLD.effective_to
        OR NEW.status IS DISTINCT FROM OLD.status
        OR NEW.last_verified_at IS DISTINCT FROM OLD.last_verified_at
        OR NEW.verified_by IS DISTINCT FROM OLD.verified_by THEN
       UPDATE legal_entry_citations
       SET review_status = 'legacy_unverified',
           reviewed_by = NULL,
           reviewed_at = NULL
       WHERE provision_id IN (
         SELECT id FROM legal_provisions WHERE source_id = NEW.id
       );
       UPDATE legal_provisions
       SET status = 'pending_review',
           reviewed_by = NULL,
           reviewed_at = NULL,
           updated_at = (now())::text
       WHERE source_id = NEW.id
         AND status = 'published';
     END IF;
     RETURN NULL;
   END $$ LANGUAGE plpgsql`,
  `CREATE OR REPLACE TRIGGER legal_sources_material_change_invalidates_rag
   AFTER UPDATE OF document_number, title, official_url, official_host,
     effective_from, effective_to, status, last_verified_at, verified_by
   ON legal_sources
   FOR EACH ROW EXECUTE FUNCTION legal_sources_rag_invalidation_fn()`,
];

// ===== Rate limit (port từ drizzle/0004_rate_limit_v1.sql) =====

export const pgRateLimitStatements: readonly string[] = [
  `CREATE TABLE IF NOT EXISTS rate_limit_buckets (
  scope text NOT NULL,
  key_hash text NOT NULL,
  window_start integer NOT NULL,
  request_count integer DEFAULT 1 NOT NULL,
  expires_at integer NOT NULL,
  CONSTRAINT rate_limit_buckets_pk
    PRIMARY KEY (scope, key_hash, window_start),
  CONSTRAINT rate_limit_buckets_scope_check
    CHECK (scope IN (
      'login-client-15m-v1',
      'login-account-60m-v1',
      'login-pair-attempt-15m-v1',
      'chat-client-60s-v1',
      'chat-client-day-v1'
    )),
  CONSTRAINT rate_limit_buckets_key_hash_check
    CHECK (key_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT rate_limit_buckets_window_check
    CHECK (
      window_start >= 0
      AND request_count >= 1
      AND expires_at > window_start
    )
)`,
  `CREATE INDEX IF NOT EXISTS rate_limit_buckets_expiry_idx
  ON rate_limit_buckets (expires_at)`,
  `CREATE TABLE IF NOT EXISTS rate_limit_penalties (
  scope text NOT NULL,
  key_hash text NOT NULL,
  window_start integer NOT NULL,
  consecutive_failures integer DEFAULT 1 NOT NULL,
  blocked_until integer DEFAULT 0 NOT NULL,
  state_version text NOT NULL,
  expires_at integer NOT NULL,
  CONSTRAINT rate_limit_penalties_pk
    PRIMARY KEY (scope, key_hash),
  CONSTRAINT rate_limit_penalties_scope_check
    CHECK (scope = 'login-pair-penalty-15m-v1'),
  CONSTRAINT rate_limit_penalties_key_hash_check
    CHECK (key_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT rate_limit_penalties_state_check
    CHECK (
      window_start >= 0
      AND consecutive_failures >= 0
      AND blocked_until >= 0
      AND state_version ~ '^[0-9a-f]{32}$'
      AND expires_at > window_start
    )
)`,
  `CREATE INDEX IF NOT EXISTS rate_limit_penalties_expiry_idx
  ON rate_limit_penalties (expires_at)`,
];

import { pgWorkflowStatements } from "./pg-workflow";

// Câu lệnh cộng thêm (additive) cho database đã bootstrap ở phiên bản cũ.
// Mọi lệnh phải idempotent và không được xóa/đổi kiểu cột đang có dữ liệu.
const pgAdditiveMigrationStatements: readonly string[] = [
  `ALTER TABLE showcases
   ADD COLUMN IF NOT EXISTS media_url text DEFAULT '' NOT NULL`,
  `ALTER TABLE legal_entries
   ADD COLUMN IF NOT EXISTS media_url text DEFAULT '' NOT NULL`,
];

export const pgSchemaVersionTable = "app_schema_version";

// Tăng giá trị này mỗi khi thêm bảng/cột mới, nếu không database đã tồn tại
// sẽ bỏ qua bootstrap và thiếu schema mới.
export const pgSchemaVersion = "2026-09-05-gamification-v1";

const createSchemaVersionTable = `
CREATE TABLE IF NOT EXISTS ${pgSchemaVersionTable} (
  version text PRIMARY KEY,
  applied_at text DEFAULT (now())::text NOT NULL
)`;

export const pgBootstrapStatements: readonly string[] = [
  createLegalSourcesTable,
  createLegalProvisionsTable,
  createLegalEntriesTable,
  createShowcasesTable,
  createLegalEntryCitationsTable,
  createContentEngagementTable,
  createContentEngagementMarksTable,
  createQuizQuestionsTable,
  createRoleplayScenariosTable,
  createRoleplayNodesTable,
  createGameBadgesTable,
  createGameProgressTable,
  createGameAwardsTable,
  ...indexStatements,
  ...triggerStatements,
  ...pgRateLimitStatements,
  ...pgWorkflowStatements,
  ...pgAdditiveMigrationStatements,
  createSchemaVersionTable,
  `INSERT INTO ${pgSchemaVersionTable} (version) VALUES ('${pgSchemaVersion}')
   ON CONFLICT (version) DO NOTHING`,
];

// Truy vấn cổng bootstrap: chỉ bỏ qua DDL khi ĐÚNG phiên bản schema hiện tại
// đã được ghi nhận. Bảng chưa tồn tại thì truy vấn lỗi và caller coi như
// "chưa sẵn sàng" — an toàn vì toàn bộ DDL đều idempotent.
export const pgSchemaVersionReadyQuery = `SELECT EXISTS (
  SELECT 1 FROM ${pgSchemaVersionTable} WHERE version = '${pgSchemaVersion}'
) AS ready`;

